# Site details
name: Ernest Ojeh
title: Ernest Ojeh &middot; UX Designer
tagline: The portfolio of Ernest Ojeh
description: Ernest Ojeh is a User Experience Designer. Currently based in Amsterdam.
url: https://ernestojeh.com
baseurl: ''
markdown: kramdown
permalink: pretty
highlighter: rouge

# Sass
sass:
  sass_dir: _scss
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-autoprefixer

autoprefixer:
  browsers:
  - last 10 versions

# permalink: /:title.html

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Collections
collections:
  photos:
    output: true

# Autopages 
autopages:
  enabled: false
