name: Ernest Ojeh
title: Ernest Ojeh &middot; UX Designer
tagline: The portfolio of Ernest Ojeh
description: Ernest Ojeh is a User Experience Designer. Currently based in Amsterdam.
url: https://ernestojeh.com
baseurl: ''
markdown: kramdown
permalink: pretty
highlighter: rouge
sass:
  sass_dir: _scss
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-redirect-from
permalink: /:title.html
exiftag:
 sources:
   - photos