backend:
    name: github
    repo: namzo/ernestojeh.com
    branch: master
    site_domain: ernestojeh.com

publish_mode: editorial_workflow
display_url: https://ernestojeh.com
media_folder: "img/post" # Media files will be stored in the repo under images/uploads

collections:
      - name: "post" # Used in routes, e.g., /admin/collections/blog
        label: "Post" # Used in the UI
        folder: "_posts" # The path to the folder where the documents are stored
        create: true # Allow users to create new documents in this collection
        slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
        fields: # The fields for each document, usually in front matter
            - {label: "layout", name: "layout", widget: "hidden", default: "post"}
            - {label: "title", name: "title", widget: "string"}
            - {label: "date", name: "date", widget: "datetime", dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm', format: 'YYYY-MM-DD HH:mm',}
            - {label: "description", name: "description", widget: "string", required: false}
            - {label: "Body", name: "body", widget: "markdown"}
editor:
    preview: false